### ISSUE TITLE
mapping error on model query

### ISSUE THREAD

**Issue by tomcounsell** [tomcounsell/popoto#14]
```py
class Column(Model):
    order = IntField()
    neurons = DictField()
```

this model gives the following error on calling `Column.query.all()`

```
Column.query.all()
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniforge/base/envs/ai/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-b523a60ea720>", line 1, in <module>
    Column.query.all()
  File "/usr/local/Caskroom/miniforge/base/envs/ai/lib/python3.8/site-packages/popoto/models/query.py", line 63, in all
    return Query.get_many_objects(self.model_class, set(redis_db_keys_list))
  File "/usr/local/Caskroom/miniforge/base/envs/ai/lib/python3.8/site-packages/popoto/models/query.py", line 124, in get_many_objects
    return [decode_popoto_model_hashmap(model, redis_hash) for redis_hash in hashes_list if redis_hash]
  File "/usr/local/Caskroom/miniforge/base/envs/ai/lib/python3.8/site-packages/popoto/models/query.py", line 124, in <listcomp>
    return [decode_popoto_model_hashmap(model, redis_hash) for redis_hash in hashes_list if redis_hash]
  File "/usr/local/Caskroom/miniforge/base/envs/ai/lib/python3.8/site-packages/popoto/models/encoding.py", line 84, in decode_popoto_model_hashmap
    return model_class(**{
  File "/usr/local/Caskroom/miniforge/base/envs/ai/lib/python3.8/site-packages/popoto/models/encoding.py", line 85, in <dictcomp>
    key_b.decode(ENCODING): decode_custom_types(msgpack.unpackb(value_b))
  File "/usr/local/Caskroom/miniforge/base/envs/ai/lib/python3.8/site-packages/msgpack_numpy.py", line 273, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: int is not allowed for map key
```

**Comment by tomcounsell** [comment]
possibly because the dict being stored in column.neurons={} has integers as keys. 
in that case, convert to bytes?
